#!/bin/sh
# postrm script for 3gpi-network-manager
#
# see: dh_installdeb(1)

set -e

SCRIPT_DIR="/etc/NetworkManager/dispatcher.d"
SCRIPT_FILES="99-3gpi-cleanup"

case "$1" in
    remove)
        for file in $SCRIPT_FILES
        do
            dpkg-statoverride --remove ${SCRIPT_DIR}/${file} >/dev/null 2>&1 || true
        done
        ;;
    
    upgrade)
        ;;
    
    purge)
        if [ "$(nmcli con | grep gsm-3gpi-soracom)" ]
        then
            nmcli con del gsm-3gpi-soracom
        fi
        if [ "$(nmcli con | grep gsm-3gpi-iij)" ]
        then
            nmcli con del gsm-3gpi-iij
        fi
        ;;
    
    failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
