#!/bin/sh
# postinst script for 3gpi-network-manager
#
# see: dh_installdeb(1)

set -e

SCRIPT_DIR="/etc/NetworkManager/dispatcher.d"
SCRIPT_FILES="99-3gpi-cleanup"

case "$1" in
    configure)
        # Change permission
        for file in $SCRIPT_FILES
        do
            dpkg-statoverride --remove ${SCRIPT_DIR}/${file} >/dev/null 2>&1 || true
            dpkg-statoverride --update add root root 755 ${SCRIPT_DIR}/${file} >/dev/null 2>&1 || true
        done
        
        # Check APN
        apns=$(nmcli -t -f NAME con | while read con; do nmcli -t -f gsm.apn con show "$con"; done)
        for apn in $apns; do [ "$apn" = "gsm.apn:soracom.io" ] && break; done
        if [ $? -ne 0 ] || [ "$apns" = "" ]
        then
            nmcli con add type gsm ifname "*" con-name gsm-3gpi-soracom apn soracom.io user sora password sora
        fi
        for apn in $apns; do [ "$apn" = "gsm.apn:iijmio.jp" ] && break; done
        if [ $? -ne 0 ] || [ "$apns" = "" ]
        then
            nmcli con add type gsm ifname "*" con-name gsm-3gpi-iij apn iijmio.jp user mio@iij password iij
        fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
